### ISSUE TITLE
Cannot jump forward

### ISSUE THREAD

**Issue by anstadnik** [quangnguyen30192/cmp-nvim-ultisnips#11]
Hi! I use an example from the README.md.
Everything works, except jumping to the next placeholder:
```lua
vim.fn.feedkeys(t("<ESC>:call UltiSnips#JumpForwards()<CR>"))
```
I've checked that this line is indeed being called. Also I've checked that if I do the same manually (press esc etc), I successfully jump to the next placeholder.
Also I've printed the value returned by
```lua
local t = function(str)
    print(vim.api.nvim_replace_termcodes(str, true, true, true))
    return vim.api.nvim_replace_termcodes(str, true, true, true)
end
```

It shows me `^[:call UltiSnips#JumpForwards()^M`, as expected.

Instead when the line is getting executed, I just get back to the normal mode. The cursor is at the end of the placeholder.
I've spent a considerable amount of time, and have no idea how to narrow down the possible reason of the issue.

I've tried to disable UltiSnips mappings:
```lua
vim.g.UltiSnipsExpandTrigger = "<NUL>"
vim.g.UltiSnipsListSnippets = "<NUL>"
vim.g.UltiSnipsJumpForwardTrigger = "<NUL>"
vim.g.UltiSnipsJumpBackwardTrigger = "<NUL>"
```
which didn't work.

**Comment by quangnguyen30192** [comment]
Hey anstanik, thanks for flagging, I just updated the example to fix it

**Comment by anstadnik** [comment]
:shrug: 
Thanks for the fix anyway!
