### ISSUE TITLE
Two questions?

### ISSUE THREAD

**Issue by medwatt** [quangnguyen30192/cmp-nvim-ultisnips#12]
1. I am not seeing ultisnips snippets in the completion menu even though I added it to `sources`. Any idea why?

2. How do you prevent a message from being displayed every time ultisnip fires?

**Comment by medwatt** [comment]
> Hi!
>
>     1. A possible reason might be that you don't have any snippet files. I suggest you to use [honza/vim-snippets](https://github.com/quangnguyen30192/cmp-nvim-ultisnips#issues)
>
>     2. I don't see any message, can you show us which message are you talking about?


[Have a look here](https://i.imgur.com/ZufeBzK.png)!

**Comment by quangnguyen30192** [comment]
Hi @medwatt 
Regarding 1., probably it's from your configuration. Does it work for you now? or could you provide me a minimal init.vim that I can help to investigate.

Regarding 2. Yes we're having this issue, I'm trying to make it silently https://github.com/quangnguyen30192/cmp-nvim-ultisnips/issues/16

**Comment by quangnguyen30192** [comment]
2. was solved by smjonas.

**Comment by quangnguyen30192** [comment]
Closed, if issue 1 still persists, just raise it again
