### ISSUE TITLE
Could UltiSnips functions be called silently?

### ISSUE THREAD

**Issue by smjonas** [quangnguyen30192/cmp-nvim-ultisnips#16]
Hey, everything works great except the only thing I noticed is that `:call UltiSnips#JumpForwards()` is output in the command line every time I press `Tab` to go to the next tabstop. Same for other function calls. Could this be made silent? 

I tried several things in the mapping like adding `<silent>` etc. but couldn't get it to work.

**Comment by quangnguyen30192** [comment]
Thanks @smjonas I also tried several approaches but couldn't make it work as well. I will investigate more.
