### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by ZachariahPang** [quangnguyen30192/cmp-nvim-ultisnips#35]
Hi, I was trying to install via vim-plug and when I do `require("cmp-nvim-ultisnips").setup()`, I got an error of Module not found.

Minimal `init.vim` to reproduce
```
call plug#begin(stdpath("data") . '/plugged')
Plug 'hrsh7th/nvim-cmp'
Plug 'quangnguyen30192/cmp-nvim-ultisnips'
call plug#end()

lua << EOF
require("cmp-nvim-ultisnips").setup {}
EOF
```

Launch with the above `init.vim` and do `:PlugInstall` and both are correctly installed but I got this error
`E5108: Error executing lua [string ":lua"]:2: module 'cmp-nvim-ultisnips' not found:`. 

Sorry, I'm new to lua, maybe I configured something wrong.

**Comment by quangnguyen30192** [comment]
Hey @ZachariahPang , we recommend using the plugin with packer. You can use vim-plug and packer at the same time. You can check here https://github.com/quangnguyen30192/cmp-nvim-ultisnips/issues/7

**Comment by smjonas** [comment]
Hey @ZachariahPang, I think this is a problem in the readme. It should be
`require('cmp_nvim_ultisnips')` instead. I will fix this now.

**Comment by quangnguyen30192** [comment]
Ah, you're right 👍

**Comment by ZachariahPang** [comment]
Thanks. This solves the importing issue.

In case this is related, the auto-completion list is still showing all snips even when they are not expandable. I tried both with
`require("cmp_nvim_ultisnips").setup{}` and `require("cmp_nvim_ultisnips").setup{show_snippets="expandable"}` and both shows non-expandable snips.

**Comment by ZachariahPang** [comment]
> Thanks. This solves the importing issue.
> 
> In case this is related, the auto-completion list is still showing all snips even when they are not expandable. I tried both with `require("cmp_nvim_ultisnips").setup{}` and `require("cmp_nvim_ultisnips").setup{show_snippets="expandable"}` and both shows non-expandable snips.

I did something wrong with my snips, it works as expected. Thanks. I'll close this issue.

**Comment by quangnguyen30192** [comment]
Thank you
