### ISSUE TITLE
Jumping not always working correctly

### ISSUE THREAD

**Issue by Astrantia** [quangnguyen30192/cmp-nvim-ultisnips#39]
With the following typescript snippet:
```
snippet log "console.log" A
console.log('${$2}', ${1})
$3
endsnippet
```
I am unable to jump out from `console.log('', asdasd|)` the cursor position where cursor is |. Instead it keeps using tab to add more spaces, and never get me in the quotes. Can you test if it is the same issue for you?

**Comment by smjonas** [comment]
Thanks for the report. Could you check with the updated recommended mappings that were just merged? We will also soon make this easier for users so you don't have to update your config all the time.

**Comment by Astrantia** [comment]
> Thanks for the report. Could you check with the updated recommended mappings that were just merged? We will also soon make this easier for users so you don't have to update your config all the time.

Unfortunately it still doesn't work. Did you try  using that snippet?

**Comment by smjonas** [comment]
Yes I tried with that snippet and it worked for me. I am currently working on a PR that improves the mappings but don't know if I have time to finish it today. That should hopefully resolve your issues. I'll let you know once it's done!

**Comment by smjonas** [comment]
Working on it here: #42

**Comment by smjonas** [comment]
Could you update your config with the recommended mappings in the readme? I have created a separate module for this so users won't have to update their config manually.
