### ISSUE TITLE
Expand Snippet function verbose when I press <Tab>

### ISSUE THREAD

**Issue by Carlosted** [quangnguyen30192/cmp-nvim-ultisnips#40]
Hi, I've seen that a few hours ago a fix was supposed to make ultisnip functions silent when pressing tab but I still see `=UltiSnips#ExpandSnippet()` when I use tab in insert mode to add space.

**Comment by smjonas** [comment]
Hey, I am working on this here: #42

**Comment by smjonas** [comment]
Could you update your config with the recommended mappings in the readme? I have created a
separate module for this so users won't have to update their config manually.
