### ISSUE TITLE
lsp tsserver breaking functionality

### ISSUE THREAD

**Issue by Astrantia** [quangnguyen30192/cmp-nvim-ultisnips#44]
I've observed interesting thing happening here. Whenever tsserver is enabled, the snippet i have posted in my another issue breaks:
```
snippet log "console.log" A
console.log('${$2}', ${1})
$3
endsnippet
```
If I disable tsserver with `:LspStop tsserver` then it works correctly. 

Not only this, but if tsserver is enabled, `<Tab>` is verbose again and writes `=UltiSnips#ExpandSnippetOrJump()` to the command line. What could be happening here?

I have updated to the latest commit and readme, and I don't even see `=UltiSnips#ExpandSnippetOrJump()` anywhere in the codebase anymore, so how does it get printed when I enable tsserver

**Comment by smjonas** [comment]
Ok this is weird. Did I get this correct: it does not happen when you have disabled cmp-nvim-ultisnips and only enabled UltiSnips? Or does it also happen then? Because in that case it is probably an UltiSnips issue.

**Comment by Astrantia** [comment]
> Ok this is weird. Did I get this correct: it does not happen when you have disabled cmp-nvim-ultisnips and only enabled UltiSnips? Or does it also happen then? Because in that case it is probably an UltiSnips issue.

I didn't think to do that, but correct, it also happens when i disable cmp-nvim-ultisnips, so it is an UltiSnips issue. Should I close this issue and open one in UltiSnips? But they don't care much about neovim over there from what I remember

**Comment by Astrantia** [comment]
It's also strange because this doesn't happen with other language servers, so there's something specific with tsserver that does it. I haven't configured tsserver with extra configs.

**Comment by smjonas** [comment]
> I didn't think to do that, but correct, it also happens when i disable cmp-nvim-ultisnips, so it is an UltiSnips issue. Should I close this issue and open one in UltiSnips? But they don't care much about neovim over there from what I remember

Yeah that's true. I will try to reproduce this first to be sure it also occurs for me.

**Comment by smjonas** [comment]
I can reproduce this by typing `'${|}'` in a .ts file (where `|` is the cursor) and hitting <kbd>Tab</kbd>. However, uninstalling tsserver does not help but removing cmp-nvim-ultisnips does. So it is indeed a bug in the new cmp-nvim-ultisnips keybindings.

**Comment by smjonas** [comment]
This might be a nvim-cmp issue as I tested it with a minimal config. I will continue later.
We should confirm this, then create a bug report on the cmp repo.

**Comment by Astrantia** [comment]
> I can reproduce this by typing `'${|}'` in a .ts file (where `|` is the cursor) and hitting Tab. However, uninstalling tsserver does not help but removing cmp-nvim-ultisnips does. So it is indeed a bug in the new cmp-nvim-ultisnips keybindings.
> 
> Update: it also appears when cmp-nvim-ultisnips is disabled (don't know why I thought it didn't happen then), so it's not a cmp-nvim-ultisnips bug. Investigating...

And from your experience it is not tied to enabling/disabling tsserver? Fixing what you found might fix the one I'm facing as well.

**Comment by smjonas** [comment]
Yes, I uninstalled tsserver and it still occurred. I now reported it on the cmp repo.

**Comment by smjonas** [comment]
Seems like hrsh7th could not reproduce it... Are you on Linux by any chance?

**Comment by Astrantia** [comment]
> Seems like hrsh7th could not reproduce it... Are you on Linux by any chance? I also could not reproduce it anymore after deleting the other plugins from my packer directory. Also could you share your plugin list so that we can narrow down which plugin(s) might cause this (that we are both using)?

I have bunch of plugins installed, so I'll try to narrow down what plugin or setting is interfering here, but it's definitely has to do with tsserver, because enabling/disabling it makes my problem go away and come back

**Comment by smjonas** [comment]
I found the cause for this issue. It is caused by [vim-snippets](https://github.com/honza/vim-snippets), specifically by this javascript snippet ([link](https://github.com/honza/vim-snippets/blob/43ed873ba09ac2d71992e773c68c75c6b85686c7/snippets/javascript/javascript.snippets#L354)):
```snippets
snippet ${
	${${1}}${0}
```
(`typescript` snippets extend from `javascript` snippets)

Honestly, I think this snippet should be removed from `vim-snippets` since it doesn't seem that useful and causes issues when expanding other snippets. However, I am not sure if it's worth opening a PR there since the plugin doesn't seem too well maintained currently.

But please feel free (you or someone else that comes across this) to open an issue there or a PR! :)
