### ISSUE TITLE
add a new mapping function?

### ISSUE THREAD

**Issue by mathjiajia** [quangnguyen30192/cmp-nvim-ultisnips#45]
Hi, thanks for this fantastic plugin.

Since I do not want to integrate too many functions in the `Tab` key.
Actually , I use the default jump key of `UltiSnips`, which is `C+J`.
Could you add a new function `expand(fallback)`.

Something like below:
```
function M.expand(fallback)
   if cmp.get_selected_entry() == nil and vim.fn["UltiSnips#CanExpandSnippet"]() == 1 then
     t("<Plug>(cmpu-expand)")
   elseif cmp.visible() then
     cmp.select_next_item()
   else
     fallback()
   end
 end
```

Thanks

**Comment by quangnguyen30192** [comment]
> I would argue that expand_or_jump_forward should be the default for new users since it feels intuitive

I feel good 👍  let's do it

**Comment by mathjiajia** [comment]
> I think this is a nice idea for users that prefer separate mappings for jumping between tabstops and selecting the next completion item. Still, I would argue that `expand_or_jump_forward` should be the default for new users since it feels intuitive. Would you agree? I think I will add this later (but the readme will also have to be updated).

Thank you.

**Comment by smjonas** [comment]
Once #48 is merged (soon), you can achieve your desired behaviour like this:
```lua
["<Tab>"] = cmp.mapping(
  function(fallback)
    cmp_ultisnips_mappings.compose({ "expand", "select_next_item" })(fallback)
  end,
  { "i", "s", [[ "c" to enable the mapping in command mode ]] }
),
["<S-Tab>"] = cmp.mapping(
  function(fallback)
    cmp_ultisnips_mappings.compose({ "select_prev_item" })(fallback)
  end,
  { "i", "s", [[ "c" to enable the mapping in command mode ]] }
)
```

**Comment by mathjiajia** [comment]
Thank you so much.
That looks great!
