### ISSUE TITLE
Disabling autotrigger causes error

### ISSUE THREAD

**Issue by medwatt** [quangnguyen30192/cmp-nvim-ultisnips#49]
I have the `autotrigger` option of ultisnips disabled for performance reasons. More on this issue can be found [here](https://github.com/SirVer/ultisnips/issues/1202#issuecomment-611351193).

```python
if has('nvim')
    au VimEnter * if exists('#UltiSnips_AutoTrigger')
        \ |     exe 'au! UltiSnips_AutoTrigger'
        \ |     aug! UltiSnips_AutoTrigger
        \ | endif
endif
```

Using the above code with this plugin produces an error every time a key is pressed.

**Comment by smjonas** [comment]
Could you share some additional info on how to reproduce this issue? Where did you put that code? What is the exact error message? Which snippet definitions are you using? I added this to my `.vimrc` (and I can confirm `A` snippets are not triggered automatically anymore) but I can't reproduce this issue.

**Comment by medwatt** [comment]
I am using Neovim version 0.6. The code I provided in the first post is inside the config file I have for ultisnips.

Here's my `cmp` config:

```lua
local present, cmp = pcall(require, "cmp")

local has_any_words_before = function()
    if vim.api.nvim_buf_get_option(0, "buftype") == "prompt" then
        return false
    end
    local line, col = unpack(vim.api.nvim_win_get_cursor(0))
    return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end

local press = function(key)
    vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(key, true, true, true), "n", true)
end

cmp.setup {

    snippet = {
        expand = function(args)
            vim.fn["UltiSnips#Anon"](args.body)
        end,
    },

    completion = {
        completeopt = "menu,menuone,noselect",
        keyword_length = 1,
    },

    sources = {
        { name = "ultisnips" },
        { name = "nvim_lsp" },
        { name = "buffer" },
        { name = "path" },
    },

    mapping = {


        ["<C-e>"] = cmp.mapping.close(),
        ["<CR>"] = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = true }),


        ["<C-Space>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
                if vim.fn["UltiSnips#CanExpandSnippet"]() == 1 then
                    return press("<C-R>=UltiSnips#ExpandSnippet()<CR>")
                end

                cmp.select_next_item()
            elseif has_any_words_before() then
                press("<Space>")
            else
                fallback()
            end
        end, {
        "i",
        "s",
    }),

    ["<Tab>"] = cmp.mapping(function(fallback)
        if vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
            press("<ESC>:call UltiSnips#JumpForwards()<CR>")
        elseif cmp.visible() then
            cmp.select_next_item()
        elseif has_any_words_before() then
            press("<Tab>")
        else
            fallback()
        end
    end, {
    "i",
    "s",
}),

["<S-Tab>"] = cmp.mapping(function(fallback)
    if vim.fn["UltiSnips#CanJumpBackwards"]() == 1 then
        press("<ESC>:call UltiSnips#JumpBackwards()<CR>")
    elseif cmp.visible() then
        cmp.select_prev_item()
    else
        fallback()
    end
end, {
"i",
"s",
    }),
},
}
```

I am using the default configuration for ultisnips. With the autotrigger disabled, when I am insert mode and press any character, I get the following ![error](https://i.imgur.com/eWiJ6rp.png).

**Comment by smjonas** [comment]
Thank you. Possibly a duplicate of #46? Are you using the latest version of this plugin? Also, we have now added recommended mapping functions you can call - see readme (they do the same as your code).

**Comment by medwatt** [comment]
I just updated and tried the recommended settings. I'm still getting the same error.

**Comment by smjonas** [comment]
Ok this is weird. Just to be 100% sure: everything works correctly when autotrigger is enabled? I will look into it.

**Comment by medwatt** [comment]
Have a look at the video to see exactly what is going on. While experimenting, I noticed that if I press the tab key by itself while in insert mode, the problem does not occur

https://user-images.githubusercontent.com/17733465/145469155-73941eaa-5a9e-4014-9452-2885fb20784e.mp4

.

**Comment by smjonas** [comment]
Could you try this PR? #51
I suspect it is some kind of loading order problem, seems like UltiSnips is not available yet when cmp_nvim_ultisnips is ready.
So I tried to source the UltiSnips file as cmp_nvim_ultisnips starts.

**Comment by medwatt** [comment]
I haven't tested it extensively, but the issue I reported is now gone.

**Comment by smjonas** [comment]
Wow I'm a bit surprised that it worked, thanks for testing!
