### ISSUE TITLE
jump to next tabstop without filling current one

### ISSUE THREAD

**Issue by JoseConseco** [quangnguyen30192/cmp-nvim-ultisnips#5]
I cant jump to next tabstop, unless I will fill the current one.  For example for this snippet:

```
snippet integer "IntProperty"
$1: bpy.props.IntProperty(name="test", description='', default=${2: 1}, min=0, max=100, subtype='PERCENTAGE')$0
```
If I  want to leave default value at $2,  I press < tab > but it wont jump forward  to $0 (only using ultiSnip build-in map < c-j >  work for jump) .  If I enter anything at $2, then I can < tab > jump forward no problem. It feels almost like I can jump only from insert mode  (and select mode jump wont work)

My mappings:

```lua
	mapping = {
		['<C-p>'] = cmp.mapping.select_prev_item(),
		['<C-n>'] = cmp.mapping.select_next_item(),
		['<S-Tab>'] = cmp.mapping(function(fallback)
			if vim.fn["UltiSnips#CanJumpBackwards"]() == 1 then
				vim.fn.feedkeys(t("<C-R>=UltiSnips#JumpBackwards()<CR>"))
			elseif vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(t("<C-p>"), "n")
			elseif check_back_space() then
				vim.fn.feedkeys(t("<S-tab>"), "n")
			else
				vim.fn.feedkeys(t("<S-tab>"), "n")
			end
		end, { "i", "s"}),
		['<Tab>'] = cmp.mapping(function(fallback)
			-- print('can jump ='..vim.inspect(vim.fn["UltiSnips#CanJumpForwards"]()))
			if vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
				vim.fn.feedkeys(t("<C-R>=UltiSnips#JumpForwards()<CR>"))
			elseif vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(t("<C-n>"), "n")
			elseif check_back_space() then
				vim.fn.feedkeys(t("<tab>"), "n")
			else
				vim.fn.feedkeys(t("<tab>"), "n")
			end
		end, { "i", "s"}),
		['<C-d>'] = cmp.mapping.scroll_docs(-4),
		['<C-f>'] = cmp.mapping.scroll_docs(4),
		['<C-e>'] = cmp.mapping.close(),
		['<CR>'] = cmp.mapping.confirm({ -- remapped at bottom by autopairs
			behavior = cmp.ConfirmBehavior.Replace,
			select = false,
		}),
		-- ['<C-Space>'] = cmp.mapping.complete(),
		['<C-Space>'] = cmp.mapping(function(fallback)
			-- print(vim.inspect(vim.fn.complete_info()))
			if vim.fn.pumvisible() == 1 then
				if vim.fn.complete_info()["selected"] ~= -1 then
					if vim.fn["UltiSnips#CanExpandSnippet"]() == 1 then
						return vim.fn.feedkeys(t("<C-R>=UltiSnips#ExpandSnippet()<CR>"))
					else
						vim.fn.feedkeys(t("<cr>"), "n")
          end
				else
					vim.fn.feedkeys(t("<C-e>"), "n")
				end
			elseif check_back_space() then
				vim.fn.feedkeys(t("<cr>"), "n")
			else
				fallback()
			end
		end, { "i", "s", }),
	},

```

I tried to create separate mapping  

`snoremap <tab> "<C-R>=UltiSnips#JumpForwards()<CR>"`

but then using tab on $2 will create   double-quote character for no reason (not sure why). I also tried remapping g:UltiSnipsJumpForwardTrigger to tab in ultisnips config, but then in conflicts with tab in cmp.   Any ideas what is going on?  WHy:
`if vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
				vim.fn.feedkeys(t("<C-R>=UltiSnips#JumpForwards()<CR>"))`  
wont jump to next tab if I wont fill in $2  ?

**Comment by quangnguyen30192** [comment]
Thanks for reporting,

> I tried to create separate mapping
snoremap <tab> "<C-R>=UltiSnips#JumpForwards()<CR>"
but then using tab on $2 will create double-quote character for no reason (not sure why)

it should be
```
snoremap <Tab> <ESC>:call UltiSnips#JumpForwards()<CR>
```

I'm investigating why it doesn't work by the current mapping ...

**Comment by quangnguyen30192** [comment]
Seems as of now, 's' map does not work as it mentioned from [nvim-cmp](https://github.com/hrsh7th/nvim-cmp#mapping-type-tablestring-funfallback-function)
```
		['<Tab>'] = cmp.mapping(function(fallback)
			...
		end, { "i", "s"}),
```
you can check like:
```
:verbose imap <tab>
```
it has the mapping, but 
```
:verbose smap <tab>
```
it doesn't have any mapping.

For now, you can use as a workaround
```
snoremap <Tab> <ESC>:call UltiSnips#JumpForwards()<CR>
```

I will raise this issue with nvim-cmp author

**Comment by quangnguyen30192** [comment]
Hey, thanks, that was a good finding. I will update README for this.
