### ISSUE TITLE
What does the snippet calling UltiSnips#Anon do

### ISSUE THREAD

**Issue by NilsIrl** [quangnguyen30192/cmp-nvim-ultisnips#6]
What does the following snippet in the README do?

```lua
snippet = {
  expand = function(args)
    vim.fn["UltiSnips#Anon"](args.body)
  end,
},
```

**Comment by quangnguyen30192** [comment]
you better ask this question for the author https://github.com/hrsh7th/nvim-cmp#basic-configuration

**Comment by quangnguyen30192** [comment]
reference https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L405
