### ISSUE TITLE
How to install with Vim-Plug

### ISSUE THREAD

**Issue by krillin666** [quangnguyen30192/cmp-nvim-ultisnips#7]
Thanks for the fix, any idea how one should proceed to install this with Vim Plug ?

**Comment by quangnguyen30192** [comment]
This plugin is just a source extension of https://github.com/hrsh7th/nvim-cmp, which is written in lua. Then using with packer is recommended.

You could use wbthomason/packer.nvim and Vim plug at the same time without any conflicts (I'm using packer.nvim and vim plug at the same time as well)

But, we can use vim vim plug as below
```vim
Plug 'quangnguyen30192/cmp-nvim-ultisnips'
Plug 'hrsh7th/nvim-cmp'
lua require 'cmp-config'
```

You will need to create a lua file under ~/.config/nvim/lua/cmp-config.lua and put everything in the config function from the README
```lua
config = function()
...
end
```

**Comment by quangnguyen30192** [comment]
Or you could use lua heredoc right in vim file as the guy [here](https://www.reddit.com/r/neovim/comments/pmlt5c/need_help_with_auto_complete/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) is doing

**Comment by krillin666** [comment]
Thank you for the help !

**Comment by DinkyTrady** [comment]
@quannguyen30192 the comment in reddit was removed.

**Comment by quangnguyen30192** [comment]
@DinkyTrady here you are

```

Plug 'hrsh7th/nvim-cmp'
Plug 'quangnguyen30192/cmp-nvim-ultisnips'
call plug#end()

lua << EOF
require("cmp-nvim-ultisnips").setup {}
EOF
```

**Comment by quangnguyen30192** [comment]
Hey @DinkyTrady do you want to install with vimplug?

**Comment by DinkyTrady** [comment]
@quangnguyen30192 yes, but now i can setup and configure it.
