### ISSUE TITLE
Using tab to jump forward leaves a space before jumping forward

### ISSUE THREAD

**Issue by medwatt** [quangnguyen30192/cmp-nvim-ultisnips#74]
The relevant part of my config is given below along with a screen recording. I currently have `Tab` mapped to just jump forward. When I'm inside a snippet and the completion menu pops up, pressing `Tab` does not automatically jump to the next place holder. Instead, it inserts a space. It's only after that that I can jump forward.

```python

["<Tab>"] = cmp.mapping(
    function(fallback)
        cmp_ultisnips_mappings.compose {"jump_forwards"}(fallback)
    end, {"i", "s"}),

["<S-Tab>"] = cmp.mapping(
    function(fallback)
        cmp_ultisnips_mappings.compose {"jump_backwards"}(fallback)
    end, {"i", "s"}),
```

![nvim](https://user-images.githubusercontent.com/17733465/164645064-e17a861f-82bb-497a-b889-77631300cab4.gif)

**Comment by quangnguyen30192** [comment]
Can you give us your minimal current config?

**Comment by quangnguyen30192** [comment]
I could reproduce the issue, working on it

**Comment by smjonas** [comment]
Thanks for reporting, it should be fixed now :)

**Comment by quangnguyen30192** [comment]
Hey @smjonas  I think he wanted to confirm the selected entry and then press <tab> to jump to the next stop

**Comment by smjonas** [comment]
In this case, wouldn't that always select the first entry only? I think it makes more sense if the confirm action is mapped to a different key. In this example I use `<C-f>` and it seems to show the correct behaviour:

![cmp_nvim_ultisnips_74](https://user-images.githubusercontent.com/40792180/164699113-b8dda9f9-7bb2-431e-9126-a306898198cc.gif)

@medwatt Any comments?

**Comment by quangnguyen30192** [comment]
If mapping the `confirm` behavior to a different key then it's fine. But it would be more flexible if we introduce `confirm` mapping in the compose then the user could combine it with whatever he wants. E.g

```
local function has_item_selected()
  return cmp.visible() and cmp.get_selected_entry() ~= nil
end

-- The <Plug> mappings are defined in autoload/cmp_nvim_ultisnips.vim.

local actions = {
   .....
   select_item = {
    condition = { has_item_selected },
    command = { cmp.confirm }
  }
  ....
}

```

Then in user mapping
```
["<Tab>"] = cmp.mapping(
    function(fallback)
        cmp_ultisnips_mappings.compose {"select_item", "jump_forwards"}(fallback)
    end, {"i", "s"}),
 ```

**Comment by smjonas** [comment]
@quangnguyen30192 That seems like a good idea. Maybe we can let users override the actions table like
```lua
mappings = {
    actions = { ... }
}
```
But as I understand it, the original issue was still solved by the PR, right? Any comments, @medwatt?
