### ISSUE TITLE
Mirrored tabstops don't work

### ISSUE THREAD

**Issue by NilsIrl** [quangnguyen30192/cmp-nvim-ultisnips#8]
Once the completion menu appears when they're being filled, they just stop working.

I've tested by disabling nvim-cmp and using <C-p> and that works which means the issue is specific to nvim-cmp.

**Comment by quangnguyen30192** [comment]
Seems you didn't set up nvim cmp properly, check basic configuration. I guess you should set

vim.o.completeopt = "menuone,noselect"

**Comment by NilsIrl** [comment]
Set that is correct I don't have noselect however that is intended. Regardless of that it works with noselect but then if I confirm a choice using <tab> it stops working.

**Comment by quangnguyen30192** [comment]
As this is specific for nvim-cmp, Could you raise this issue in nvim-cmp?

**Comment by quangnguyen30192** [comment]
What is your config for ultisnips?

**Comment by quangnguyen30192** [comment]
Closed as the reporter seems is not active anymore
