### ISSUE TITLE
Many auto-snippets can not be trigger

### ISSUE THREAD

**Issue by ChasingZenith** [quangnguyen30192/cmp-nvim-ultisnips#83]
```python
snippet '(red|blue|gray|green)tt' "redtt \color{color}{text}" rA
\\color{`!p snip.rv = match.group(1)`}{${1:${VISUAL}}}
endsnippet
```

I find this snippet and many other auto-triggered snippet just occasionally work.

On my machine, if I press `redttredtt`, only the first one will  trigger the snippet.

Can you guys test on this case?

**Comment by quangnguyen30192** [comment]
Hey, thank you for reporting this.

You miss `i` option that triggers t[he in-word expansion ](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L676)

```
snippet '(red|blue|gray|green)tt' "redtt \color{color}{text}" irA
\\color{`!p snip.rv = match.group(1)`}{${1:${VISUAL}}}
endsnippet
```
