### ISSUE TITLE
ultisnips not working with the latest neovim nightly

### ISSUE THREAD

**Issue by Trid-collab** [quangnguyen30192/cmp-nvim-ultisnips#9]
I have noticed that the Ultisnips options have stopped working with latest neovim nightly release. Have checked that it works with the rolled back stable release.

Is there something we need to do to fix in the new release

**Comment by quangnguyen30192** [comment]
Thanks, I will check

**Comment by rebelot** [comment]
please see https://github.com/hrsh7th/nvim-cmp/issues/241#issuecomment-925831381

**Comment by quangnguyen30192** [comment]
Just installed neovim nightly and there are many plugins installed on my machine stop working

**Comment by quangnguyen30192** [comment]
Let's see if I could do something from cmp-nvim-ultisnips's side

**Comment by quangnguyen30192** [comment]
@captainko this is how the guys here https://github.com/hrsh7th/nvim-cmp/issues/241#issuecomment-925831381 fix it
```
  use {'honza/vim-snippets', rtp = '.'}
```

**Comment by captainko** [comment]
Oh thanks, It works like charms.

**Comment by rebelot** [comment]
I think this is it.. https://github.com/neovim/neovim/pull/15632

**Comment by quangnguyen30192** [comment]
neovim nightly is not supposed to be stable. yeah surely it will be hiccup sometimes

**Comment by Trid-collab** [comment]
@rebelot  thank you  use {'honza/vim-snippets', rtp = '.'} helped resolved the issue
However @quangnguyen30192   I also noticed that the I am not able to circulate the snippet placeholders using tabs like it was working before. Its not even working in the neovim stable release. When I am typing in the snippet placeholder the autocompletes are popping up while I am typing. On completion I am not able to use the tabs to move to the next placeholder.

**Comment by rebelot** [comment]
> However @quangnguyen30192 I also noticed that the I am not able to circulate the snippet placeholders using tabs like it was working before. Its not even working in the neovim stable release. When I am typing in the snippet placeholder the autocompletes are popping up while I am typing. On completion I am not able to use the tabs to move to the next placeholder.

You’re welcome, maybe `opt=true` should also work and might be more elegant. My two cents on “supertab”: just use <c-j>/<c-k> and stop bothering rewriting your config every other day. After a few hours you think it’s working, then you notice macros don’t work anymore, you manage to fix it, then you update neovim or cmp and you have to start again. The amount of issues and config bloatware related to tab mappings is fenomenal.

**Comment by Trid-collab** [comment]
@rebelot I have tried putting opt=true but doesn't seem to be working - I have tried use {'honza/vim-snippets', rtp = '.', opt=true}
Am I correct in doing it . Pardon me if this is a trivial clarification. I am new to this.

**Comment by quangnguyen30192** [comment]
@Trid-collab probably you need to set

```lua
vim.g.UltiSnipsRemoveSelectModeMappings = 0
```
or 

```vim
let g:UltiSnipsRemoveSelectModeMappings = 0
```

**Comment by Trid-collab** [comment]
The done the same but still the place holder issue remains. I was also reverted back to the stable version

This is my plugin setup

use({
		"SirVer/ultisnips",
		requires = { "honza/vim-snippets" },
		config = function()
			vim.g.UltiSnipsRemoveSelectModeMappings = 0
		end,
	})

and my cmp mapping setup

	mapping = {
		["<C-p>"] = cmp.mapping.select_prev_item(),
		["<C-k>"] = cmp.mapping.select_prev_item(),
		["<C-n>"] = cmp.mapping.select_next_item(),
		["<C-j>"] = cmp.mapping.select_next_item(),
		["<C-d>"] = cmp.mapping.scroll_docs(-4),
		["<C-f>"] = cmp.mapping.scroll_docs(4),
		["<C-e>"] = cmp.mapping.close(),
		["<CR>"] = cmp.mapping.confirm({
			behavior = cmp.ConfirmBehavior.Insert,
			select = true,
		}),
		["<C-Space>"] = cmp.mapping(function(fallback)
			if vim.fn.pumvisible() == 1 then
				if vim.fn["UltiSnips#CanExpandSnippet"]() == 1 then
					return vim.fn.feedkeys(t("<C-R>=UltiSnips#ExpandSnippet()<CR>"))
				end
				vim.fn.feedkeys(t("<C-n>"), "n")
			elseif check_back_space() then
				vim.fn.feedkeys(t("<cr>"), "n")
			else
				fallback()
			end
		end, {
			"i",
			"s",
		}),
		["<Tab>"] = cmp.mapping(function(fallback)
			if vim.fn.complete_info()["selected"] == -1 and vim.fn["UltiSnips#CanExpandSnippet"]() == 1 then
				vim.fn.feedkeys(t("<C-R>=UltiSnips#ExpandSnippet()<CR>"))
			elseif vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
				vim.fn.feedkeys(t("<ESC>:call UltiSnips#JumpForwards()<CR>"))
			elseif vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(t("<C-n>"), "n")
			elseif check_back_space() then
				vim.fn.feedkeys(t("<tab>"), "n")
			else
				fallback()
			end
		end, {
			"i",
			"s",
		}),
		["<S-Tab>"] = cmp.mapping(function(fallback)
			if vim.fn["UltiSnips#CanJumpBackwards"]() == 1 then
				return vim.fn.feedkeys(t("<C-R>=UltiSnips#JumpBackwards()<CR>"))
			elseif vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(t("<C-p>"), "n")
			else
				fallback()
			end
		end, {
			"i",
			"s",
		}),
	},

**Comment by Trid-collab** [comment]
@quangnguyen30192 I have reverted back to neovim stable. The Ultisnips are showing in the autocomplete now and am able to select. 
But the supertab option is not working - in order to circulate between the placeholders. I have tried following the setup in your readme. Whenever I am trying to type something in the placement autocomplete is poping up which I believe hindering the circulation through the placeholders

**Comment by quangnguyen30192** [comment]
Hey thanks, checking it now

**Comment by Trid-collab** [comment]
found out the offending piece of code in cmp setup which was not allowing the tab to work
completion = { completeopt = "menu,menuone,noinsert" }, -- removing this has helped the supertab to work

But even then <S-Tab> is working weirdly Could you check- Basically when I am circulating back using the <S-Tab> its going to immediate earlier placeholder but then if we don't re type the placeholder and simply want to go the next above it deletes the placeholder. So say suppose if I am using ife and I come to the last placeholder and want to change the topmost one without changing the second one in between doing S-Tab deletes the one in between which has not been changed 

This doesn't happen when using @rebelot's  suggestions C-K to go backwards

**Comment by quangnguyen30192** [comment]
> completion = { completeopt = "menu,menuone,noinsert" }, -- removing this has helped the supertab to work

That's weird, this is the setting recommended by cmp author

Can you try with 

```lua
	["<S-Tab>"] = cmp.mapping(function(fallback)
		if vim.fn["UltiSnips#CanJumpBackwards"]() == 1 then
			return vim.fn.feedkeys(t("<ESC>:call UltiSnips#JumpBackwards()<CR>"))
		elseif vim.fn.pumvisible() == 1 then
			vim.fn.feedkeys(t("<C-p>"), "n")
		else
			fallback()
		end
	end
```

**Comment by Trid-collab** [comment]
Perfecto. It works. like C-K
Just one question whenever I doing a forward jump or backward jump  on the placeholder its printing :call UltiSnips#JumpForward or :call UltiSnips#JumpBackward

Its no harm but just curious
![image](https://user-images.githubusercontent.com/61322708/134774077-64765f2f-fb32-46f0-917a-d86c1599aa5d.png)

Also a question to you and @rebelot does using Utlisnip slow down language server especially pyright compared to Luasbip or others. 
I have started liking UltiSnip more because its more rich in snippet options

**Comment by Trid-collab** [comment]
> > However @quangnguyen30192 I also noticed that the I am not able to circulate the snippet placeholders using tabs like it was working before. Its not even working in the neovim stable release. When I am typing in the snippet placeholder the autocompletes are popping up while I am typing. On completion I am not able to use the tabs to move to the next placeholder.
> 
> You’re welcome, maybe `opt=true` should also work and might be more elegant. My two cents on “supertab”: just use `<c-j>/<c-k>` and stop bothering rewriting your config every other day. After a few hours you think it’s working, then you notice macros don’t work anymore, you manage to fix it, then you update neovim or cmp and you have to start again. The amount of issues and config bloatware related to tab mappings is fenomenal.

**Comment by quangnguyen30192** [comment]
you had better ask ultisnips author. IMO Ultisnips is more way friendly, easy to learn, versatile and has rich support from overall languages. Probably comparing to the other snippet engines, it slows, but how much is it? 

I have been using ultisnips for 3 years and had no problem with performance, If your laptop is not produced in 1970 then I would say just use it

**Comment by quangnguyen30192** [comment]
> Just one question whenever I doing a forward jump or backward jump on the placeholder its printing :call UltiSnips#JumpForward or :call UltiSnips#JumpBackward

not sure if cmp mapping support `silent` mode

**Comment by smjonas** [comment]
> @captainko this is how the guys here [hrsh7th/nvim-cmp#241 (comment)](https://github.com/hrsh7th/nvim-cmp/issues/241#issuecomment-925831381) fix it
>
> ```
>   use {'honza/vim-snippets', rtp = '.'}
> ```

@quangnguyen30192  Is this workaround still needed since https://github.com/neovim/neovim/pull/15632 has been merged a while ago? I haven't noticed any problems with vim-snippets while not setting the rtp manually. Can we remove that section from the readme?

**Comment by quangnguyen30192** [comment]
Sure, since the root cause was fixed, we don't need that in the readme
